#!/bin/bash

export PYTHONPATH=~/git/lockr
PEERS=localhost:$3,localhost:$4,localhost:$5,localhost:$6

while true; do
    echo
    python ~/git/lockr/msgio lockr --node $1 --port $2 --peers $PEERS
done
